title: Extracting and Interpreting Acoustic data with Praat and Parselmouth
description: A technical tutorial for harnessing the power of Praat with Python
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
